name: froom_generator
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 2.0.0
homepage: https://wilinz.github.io/froom/
repository: https://github.com/wilinz/froom
issue_tracker: https://github.com/wilinz/froom/issues
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^7.4.0
  build: ^2.1.0
  build_config: ^1.1.2
  code_builder: ^4.10.1
  collection: ^1.19.1
  froom_annotation:
    path: ../froom_annotation/
  meta: ^1.16.0
  source_gen: ^2.0.0
  strings: ^4.0.0

dev_dependencies:
  build_test: ^2.2.3
  dart_style: ^3.1.0
  mockito: ^5.4.6
  path: ^1.9.1
  test: ^1.26.2
  test_cov:
    git:
      url: https://github.com/wilinz/test_cov
