name: froom_generator
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the dev dependency.
version: 4.0.0
homepage: https://wilinz.github.io/froom/
repository: https://github.com/wilinz/froom
documentation: https://wilinz.github.io/froom
issue_tracker: https://github.com/wilinz/froom/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^8.1.1
  build: ^4.0.0
  build_config: ^1.2.0
  code_builder: ^4.10.1
  collection: ^1.19.1
#  froom_annotation: ^2.0.0
  froom_annotation:
    path: ../froom_annotation/
  meta: ^1.16.0
  source_gen: ^4.0.1
  strings: ^4.0.1
  pub_semver: ^2.2.0

dev_dependencies:
  build_test: ^3.3.2
  dart_style: ^3.1.1
  mockito: ^5.5.1
  path: ^1.9.1
  test: ^1.26.3
  test_cov:
    git:
      url: https://github.com/wilinz/test_cov
