name: froom_common
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 2.0.4
homepage: https://froom.codes

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
#  froom_annotation: ^2.0.0
  froom_annotation:
    path: ../froom_annotation/
  meta: ^1.16.0
  path: ^1.9.1
  sqflite_common: ^2.5.6
  sqlparser: ^0.41.1

dev_dependencies:
  build_runner: ^2.7.0
  collection: ^1.19.1
#  froom_generator: ^2.0.0
  froom_generator:
    path: ../froom_generator/
  sqflite_common_ffi: ^2.3.6
  test: ^1.26.3
  matcher: ^0.12.17
  mockito: ^5.5.0
