name: froom_annotation
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  Don't use this package directly. Import the froom package instead.
version: 2.0.0
homepage: https://wilinz.github.io/froom/
repository: https://github.com/wilinz/froom
issue_tracker: https://github.com/wilinz/froom/issues

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  meta:
