name: froom
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 2.0.2
homepage: https://wilinz.github.io/froom/
repository: https://github.com/wilinz/froom
issue_tracker: https://github.com/wilinz/froom/issues

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  collection: ^1.18.0
  froom_annotation:
    path: ../froom_annotation/
  froom_common:
    path: ../froom_common/
  flutter:
    sdk: flutter
  meta: ^1.16.0
  path: ^1.9.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  sqflite_common_ffi_web: ^1.0.0
  sqlparser: ^0.41.1

dev_dependencies:
  build_runner: ^2.4.8
  froom_generator:
    path: ../froom_generator
  flutter_test:
    sdk: flutter
  matcher: ^0.12.16+1
  mockito: ^5.4.4