name: froom
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 3.0.2
homepage: https://wilinz.github.io/froom/
repository: https://github.com/wilinz/froom
documentation: https://wilinz.github.io/froom
issue_tracker: https://github.com/wilinz/froom/issues

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  collection: ^1.19.1
  froom_annotation:
    path: ../froom_annotation/
  froom_common:
    path: ../froom_common/
  meta: ^1.16.0
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.6
  sqflite_common_ffi_web: ^1.0.1+1
  sqlparser: ^0.41.1

dev_dependencies:
  build_runner: ^2.8.0
  froom_generator:
    path: ../froom_generator
  matcher: ^0.12.17
  mockito: ^5.5.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  windows: