name: publish_kit
description: Dart script for managing package releases.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  path: ^1.9.1
  yaml: ^3.1.3
  yaml_edit: ^2.2.2
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
