name: publish_kit
description: Dart script for managing package releases.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  path: ^1.9.0
  yaml: ^3.1.0
  yaml_edit: ^2.2.1
  args: ^2.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
