name: CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  froom-annotation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    container:
      image: dart:3.3.0

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: froom_annotation
        run: dart pub get

      - name: Analyze
        working-directory: froom_annotation
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Format
        working-directory: froom_annotation
        run: dart format --output=none --set-exit-if-changed .

  froom-generator:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    container:
      image: dart:3.3.0

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: froom_generator
        run: dart pub get

      - name: Analyze
        working-directory: froom_generator
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Format
        working-directory: froom_generator
        run: dart format --output=none --set-exit-if-changed .

      - name: Run tests
        working-directory: froom_generator
        run: dart run test_cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: froom_generator
          file: ./froom_generator/coverage/lcov.info

  froom:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install dependencies
        run: flutter packages get
        working-directory: froom

      - name: Run generator
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
        working-directory: froom_common

      - name: Analyze
        run: flutter analyze
        working-directory: froom

      - name: Install SQLite
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get -y update
          sudo apt-get -y install sqlite3 libsqlite3-dev

      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.info
        working-directory: froom_common

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: froom
          file: ./froom_common/coverage/lcov.info

  example:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter packages get
        working-directory: example

      - name: Analyze
        run: flutter analyze
        working-directory: example

      - name: Install SQLite
        run: |
          sudo apt-get -y update
          sudo apt-get -y install sqlite3 libsqlite3-dev

      - name: Run tests
        run: flutter test
        working-directory: example
